"""empty message

Revision ID: 85b179f619ca
Revises: f2d1fe460d02
Create Date: 2020-02-09 11:22:26.413229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b179f619ca'
down_revision = 'f2d1fe460d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Answer', 'create_time')
    # ### end Alembic commands ###
